[theme]
base = "dark"

primaryColor = "#8b0000"
backgroundColor = "#0b0b0f"
secondaryBackgroundColor = "#121217"
textColor = "#e6e6eb"

linkColor = "#b11226"
codeBackgroundColor = "#0f0f14"

baseRadius = "small"
buttonRadius = "small"
showWidgetBorder = true

[theme.sidebar]
backgroundColor = "#0e0e13"
secondaryBackgroundColor = "#121217"
textColor = "#e6e6eb"
primaryColor = "#8b0000"
